apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "cert-api-chart.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "cert-api-chart.fullname" . }}
  maxReplicas: {{ .Values.replicaCount }}
  targetCPUUtilizationPercentage: {{ .Values.targetCPUUtilizationPercentage }}
