version: '1.0'
services:
  web:
    image: 
    # environment:
    ports: 3000:3000
    # depends_on:
    deploy: 
      replicas: 3
    update_config:
      parallelism: 2
      delay: 10s
    restart_policy:
      condition: on-failure
