apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myapi-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapi-deployment
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50